@startuml
!theme mars

'https://plantuml.com/class-diagram

interface Solver {
    solve()
    is_solved()
}
interface ReductionSolver
interface BeginnerLBLReduce

Solver <|-- ReductionSolver




Solver <|-- BeginnerLBLReduce
ReductionSolver <|-- BeginnerLBLReduce

class BeginnerSolver

BeginnerLBLReduce <|-- BeginnerSolver
BaseSolver <|-- BeginnerSolver

CommonOp *.. Operator
CommonOp *.. BaseSolver
CommonOp *.. Cube

SolverElement *.. Operator

SolverElement <|-- CommonOp
SolverElement <|-- L1Cross
SolverElement <|-- L1Corners
SolverElement <|-- L2
SolverElement <|-- L3Cross
SolverElement <|-- L3Corners
SolverElement <|-- NxNCenters
SolverElement <|-- NxNEdges

BeginnerSolver *-- CommonOp
BeginnerSolver *-- L1Cross
BeginnerSolver *-- L1Corners
BeginnerSolver *-- L2
BeginnerSolver *-- L3Cross
BeginnerSolver *-- L3Corners
BeginnerSolver *-- NxNCenters
BeginnerSolver *-- NxNEdges
@enduml