@startuml
!theme mars

'https://plantuml.com/class-diagram

enum SolveStep {
    ALL
    L1x
    L1
    L2
    L3
    L3x
    NxNCenters
    NxNEdges
}

class SolverResults {
    was_corner_swap: bool
    was_even_edge_parity: bool
    was_partial_edge_parity: bool
}

interface Solver {
    {abstract} solve(what: SolveStep): SolverResults
    {abstract} is_solved: bool
    {abstract} status: str
    {abstract} is_debug_config_mode: bool
    {abstract} op: Operator
    name: str
}

interface ReductionSolver
interface BeginnerLBLReduce

Solver ..> SolveStep : uses
Solver ..> SolverResults : returns

Solver <|-- ReductionSolver




Solver <|-- BeginnerLBLReduce
ReductionSolver <|-- BeginnerLBLReduce

class BeginnerSolver

BeginnerLBLReduce <|-- BeginnerSolver
BaseSolver <|-- BeginnerSolver

CommonOp *.. Operator
CommonOp *.. BaseSolver
CommonOp *.. Cube

SolverElement *.. Operator

SolverElement <|-- CommonOp
SolverElement <|-- L1Cross
SolverElement <|-- L1Corners
SolverElement <|-- L2
SolverElement <|-- L3Cross
SolverElement <|-- L3Corners
SolverElement <|-- NxNCenters
SolverElement <|-- NxNEdges

BeginnerSolver *-- CommonOp
BeginnerSolver *-- L1Cross
BeginnerSolver *-- L1Corners
BeginnerSolver *-- L2
BeginnerSolver *-- L3Cross
BeginnerSolver *-- L3Corners
BeginnerSolver *-- NxNCenters
BeginnerSolver *-- NxNEdges
@enduml