"""Help command - prints keyboard and mouse help to console."""
from __future__ import annotations

from dataclasses import dataclass

from .base import Command, CommandContext, CommandResult


@dataclass(frozen=True)
class HelpCommand(Command):
    """Command to print keyboard help to console with human-readable descriptions."""

    def execute(self, ctx: CommandContext) -> CommandResult:
        """Print comprehensive help with descriptions."""
        print("\n")
        print("=" * 95)
        print("RUBIK'S CUBE SOLVER - COMPLETE KEYBOARD & MOUSE GUIDE".center(95))
        print("=" * 95)

        print("\n" + "FACE ROTATIONS".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Rotate Right face clockwise".ljust(55) + "| R")
        print("  Rotate Right face counter-clockwise".ljust(55) + "| Shift+R")
        print("  Rotate Left face clockwise".ljust(55) + "| L")
        print("  Rotate Left face counter-clockwise".ljust(55) + "| Shift+L")
        print("  Rotate Up face clockwise".ljust(55) + "| U")
        print("  Rotate Up face counter-clockwise".ljust(55) + "| Shift+U")
        print("  Rotate Down face clockwise".ljust(55) + "| D")
        print("  Rotate Down face counter-clockwise".ljust(55) + "| Shift+D")
        print("  Rotate Front face clockwise".ljust(55) + "| F")
        print("  Rotate Front face counter-clockwise".ljust(55) + "| Shift+F")
        print("  Rotate Back face clockwise".ljust(55) + "| B")
        print("  Rotate Back face counter-clockwise".ljust(55) + "| Shift+B")

        print("\n" + "WIDE ROTATIONS (two outer layers)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Right two layers clockwise (Rw)".ljust(55) + "| Ctrl+R")
        print("  Right two layers counter-clockwise (Rw')".ljust(55) + "| Ctrl+Shift+R")
        print("  Left two layers clockwise (Lw)".ljust(55) + "| Ctrl+L")
        print("  Left two layers counter-clockwise (Lw')".ljust(55) + "| Ctrl+Shift+L")
        print("  Up two layers clockwise (Uw)".ljust(55) + "| Ctrl+U")
        print("  Up two layers counter-clockwise (Uw')".ljust(55) + "| Ctrl+Shift+U")
        print("  Down two layers clockwise (Dw)".ljust(55) + "| Ctrl+D")
        print("  Down two layers counter-clockwise (Dw')".ljust(55) + "| Ctrl+Shift+D")
        print("  Front two layers clockwise (Fw)".ljust(55) + "| Ctrl+F")
        print("  Front two layers counter-clockwise (Fw')".ljust(55) + "| Ctrl+Shift+F")
        print("  Back two layers clockwise (Bw)".ljust(55) + "| Ctrl+B")
        print("  Back two layers counter-clockwise (Bw')".ljust(55) + "| Ctrl+Shift+B")

        print("\n" + "SLICE MOVES (middle layers between faces)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Middle slice parallel to L-face (like Lw without L)".ljust(55) + "| M")
        print("  Middle slice counter-clockwise (M')".ljust(55) + "| Shift+M")
        print("  Equatorial slice parallel to D-face (like Dw without D)".ljust(55) + "| E")
        print("  Equatorial slice counter-clockwise (E')".ljust(55) + "| Shift+E")
        print("  Standing slice parallel to F-face (like Fw without F)".ljust(55) + "| S")
        print("  Standing slice counter-clockwise (S')".ljust(55) + "| Shift+S")

        print("\n" + "CUBE ROTATIONS (entire cube, not faces)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Rotate whole cube on R-axis (equiv to Rw for solved)".ljust(55) + "| X")
        print("  Rotate whole cube on R-axis counter-clockwise (X')".ljust(55) + "| Shift+X")
        print("  Rotate whole cube on U-axis (equiv to Uw for solved)".ljust(55) + "| Y")
        print("  Rotate whole cube on U-axis counter-clockwise (Y')".ljust(55) + "| Shift+Y")
        print("  Rotate whole cube on F-axis (equiv to Fw for solved)".ljust(55) + "| Z")
        print("  Rotate whole cube on F-axis counter-clockwise (Z')".ljust(55) + "| Shift+Z")

        print("\n" + "SCRAMBLING".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Scramble cube with seed 0 (animated with moves shown)".ljust(55) + "| 0")
        print("  Scramble cube with seed 1-9 (fast, not animated)".ljust(55) + "| 1-9")
        print("  Scramble from F.txt file in resources/scramble/".ljust(55) + "| `  (backtick)")
        print("  Scramble with F9 configured seed (from config.py)".ljust(55) + "| F9")
        print("  Special scramble variations (experiment)".ljust(55) + "| Shift/Alt+0-9")
        print("  Scramble with testing (animate + step-by-step debug)".ljust(55) + "| Ctrl+1-9")

        print("\n" + "SOLVING COMMANDS".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Solve entire cube (animated, see every step)".ljust(55) + "| /")
        print("  Solve entire cube instantly (no animation)".ljust(55) + "| Shift+/")
        print("  Solve Layer 1: white cross + corners".ljust(55) + "| F1")
        print("  Solve Layer 1 cross only (for practice)".ljust(55) + "| Ctrl+F1")
        print("  Solve Layer 2: middle edges around cube".ljust(55) + "| F2")
        print("  Solve Layer 3: yellow face (OLL + PLL)".ljust(55) + "| F3")
        print("  Solve Layer 3 cross only (for practice)".ljust(55) + "| Ctrl+F3")
        print("  Solve big cube centers (for 4x4, 5x5, 6x6...)".ljust(55) + "| F4")
        print("  Solve big cube edges (for 4x4, 5x5, 6x6...)".ljust(55) + "| F5")

        print("\n" + "VIEW/CAMERA CONTROL".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Rotate view around X-axis (negative direction)".ljust(55) + "| Ctrl+X")
        print("  Rotate view around X-axis (positive direction)".ljust(55) + "| Alt+X")
        print("  Rotate view around Y-axis (negative direction)".ljust(55) + "| Ctrl+Y")
        print("  Rotate view around Y-axis (positive direction)".ljust(55) + "| Alt+Y")
        print("  Rotate view around Z-axis (negative direction)".ljust(55) + "| Ctrl+Z")
        print("  Rotate view around Z-axis (positive direction)".ljust(55) + "| Alt+Z")
        print("  Pan view up/down/left/right".ljust(55) + "| Arrow keys")
        print("  Zoom in (make cube larger)".ljust(55) + "| Ctrl+Up")
        print("  Zoom out (make cube smaller)".ljust(55) + "| Ctrl+Down")
        print("  Reset view to default camera position".ljust(55) + "| Alt+C")

        print("\n" + "ANIMATION & SPEED".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Increase animation speed (faster moves)".ljust(55) + "| Shift+Up or NumPad+")
        print("  Decrease animation speed (slower moves)".ljust(55) + "| Shift+Down or NumPad-")
        print("  Pause/Resume animation (continue from where paused)".ljust(55) + "| Space")
        print("  Toggle single-step mode (pause after EACH move)".ljust(55) + "| Ctrl+Space")
        print("  Next step (when in single-step mode)".ljust(55) + "| Space")
        print("  Stop animation immediately (abort solve/scramble)".ljust(55) + "| S  (during anim)")

        print("\n" + "CUBE MODIFICATION".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Increase cube size (2x2 -> 3x3 -> 4x4...)".ljust(55) + "| =  (Equal)")
        print("  Decrease cube size (4x4 -> 3x3 -> 2x2...)".ljust(55) + "| -  (Minus)")
        print("  Reset cube to solved (all white, yellow on top)".ljust(55) + "| C")
        print("  Reset cube AND camera view to defaults".ljust(55) + "| Ctrl+C")
        print("  Undo last move (user move or solver step)".ljust(55) + "| ,  (Comma)")

        print("\n" + "SLICE RANGE (for slicing on big cubes)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Increase start layer index for slicing".ljust(55) + "| [")
        print("  Decrease start layer index for slicing".ljust(55) + "| Shift+[")
        print("  Increase end layer index for slicing".ljust(55) + "| ]")
        print("  Decrease end layer index for slicing".ljust(55) + "| Shift+]")
        print("  Reset to default slice range (all layers)".ljust(55) + "| Alt+[")

        print("\n" + "LIGHTING CONTROLS (pyglet2 backend only)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Decrease ambient light brightness (10%-150%)".ljust(55) + "| Ctrl+[")
        print("  Increase ambient light brightness (10%-150%)".ljust(55) + "| Ctrl+]")
        print("  Decrease background gray level (0%-50% darker)".ljust(55) + "| Ctrl+Shift+[")
        print("  Increase background gray level (0%-50% lighter)".ljust(55) + "| Ctrl+Shift+]")

        print("\n" + "TEXTURES (pyglet2 backend only)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Cycle through texture sets (solid -> set1 -> ...)".ljust(55) + "| Ctrl+Shift+T")
        print("  [Configure texture sets in config.py: TEXTURE_SETS]".ljust(55) + "|")
        print("  [Texture images in: src/cube/resources/faces/]".ljust(55) + "|")

        print("\n" + "SHADOWS (for LDB faces visibility)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Toggle shadow on Left face (easier to see depth)".ljust(55) + "| F10")
        print("  Toggle shadow on Down face (easier to see depth)".ljust(55) + "| F11")
        print("  Toggle shadow on Back face (easier to see depth)".ljust(55) + "| F12")

        print("\n" + "RECORDING & PLAYBACK".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Start recording moves (user and solver)".ljust(55) + "| Ctrl+P")
        print("  Stop recording moves".ljust(55) + "| Ctrl+P (again)")
        print("  Play back last recording".ljust(55) + "| P")
        print("  Play last recording in reverse (undo moves)".ljust(55) + "| Shift+P")
        print("  Delete last recording".ljust(55) + "| Alt+P")
        print("  EXAMPLE: Record -> Scramble -> Solve -> Play reverse".ljust(55) + "|")
        print("          This shows solve then unscrambles the cube".ljust(55) + "|")

        print("\n" + "DEBUG & TESTING".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Toggle animation on/off globally".ljust(55) + "| O")
        print("  Toggle solver debug mode (shows steps)".ljust(55) + "| Ctrl+O")
        print("  Toggle cube sanity check after every move (slow!)".ljust(55) + "| Alt+O")
        print("  Print debug info: camera angles, layer dist...".ljust(55) + "| I")
        print("  Run full solver tests (compares all solvers)".ljust(55) + "| T")
        print("  Rerun last test with same scramble".ljust(55) + "| Alt+T")
        print("  Rerun last scramble (rescremble same pattern)".ljust(55) + "| Ctrl+T")
        print("  Print current solver state to console (button: Diag)".ljust(55) + "|")

        print("\n" + "SOLVERS & MODES".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Switch to next available solver".ljust(55) + "| \\  (Backslash)")
        print("  Available: Beginner, LBL, Cage, Kociemba".ljust(55) + "|")

        print("\n" + "FULL MODE (focus mode)".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Toggle full mode (hide toolbar & status text)".ljust(55) + "| F9")
        print("  Exit full mode (return to normal view)".ljust(55) + "| ESC")
        print("  [Toolbar 'Full' button also toggles full mode]".ljust(55) + "|")
        print("  [Small 'X' button in top-right exits full mode]".ljust(55) + "|")

        print("\n" + "APPLICATION".ljust(55) + "| KEY")
        print("-" * 95)
        print("  Quit application".ljust(55) + "| Q")
        print("  Test annotations (developer debug)".ljust(55) + "| W")
        print("  Test special algorithm (developer debug)".ljust(55) + "| A")

        print("\n" + "=" * 95)
        print("MOUSE OPERATIONS".center(95))
        print("=" * 95)
        print("\n  Right-click + drag        -> Rotate the cube model freely in 3D space")
        print("  Left-click + drag         -> Rotate cube FACES/SLICES (smart detection)")
        print("  Alt + mouse drag          -> Pan the view (move left/right/up/down)")
        print("  Mouse wheel scroll        -> Zoom in/out (scroll up = zoom in)")
        print("  Shift + click on edge     -> Rotate slice counter-clockwise")
        print("  Ctrl + click on edge      -> Rotate slice clockwise")
        print("  Click on face center      -> Rotate face (direction based on drag)")
        print("  Click on corner piece     -> Rotate adjacent faces")

        print("\n" + "=" * 95 + "\n")
        return CommandResult(no_gui_update=True)
