"""Generate pre-computed IDA* tables and write them as a Python source file.

Run this script to regenerate _precomputed.py:
    python -m cube.domain.solver._2x2.generate_tables

The generated file contains zlib-compressed table data that loads in <50ms,
eliminating the 2-5 second BFS computation on first solve.
"""

from __future__ import annotations

import base64
import os
import zlib

from cube.domain.solver._2x2.ida_star_tables import (
    _build_perm_move_table,
    _build_pruning_table,
    _build_twist_move_table,
)


def generate() -> None:
    """Build all tables and write _precomputed.py."""
    print("Building twist_move table (729 x 9)...")
    twist_move = _build_twist_move_table()

    print("Building perm_move table (5040 x 9)...")
    perm_move = _build_perm_move_table()

    print("Building pruning table (5040 x 729) via BFS...")
    pruning = _build_pruning_table(twist_move, perm_move)

    # Convert array('H') to bytes for compression
    twist_bytes = twist_move.tobytes()
    perm_bytes = perm_move.tobytes()
    pruning_bytes = bytes(pruning)

    print(f"Raw sizes: twist={len(twist_bytes)}, perm={len(perm_bytes)}, pruning={len(pruning_bytes)}")

    # Compress with zlib (level 9 for best compression)
    twist_z = zlib.compress(twist_bytes, 9)
    perm_z = zlib.compress(perm_bytes, 9)
    pruning_z = zlib.compress(pruning_bytes, 9)

    print(f"Compressed: twist={len(twist_z)}, perm={len(perm_z)}, pruning={len(pruning_z)}")

    # Encode as base85 (more compact than base64 for Python source)
    twist_b85 = base64.b85encode(twist_z)
    perm_b85 = base64.b85encode(perm_z)
    pruning_b85 = base64.b85encode(pruning_z)

    print(f"Base85: twist={len(twist_b85)}, perm={len(perm_b85)}, pruning={len(pruning_b85)}")

    # Write the Python source file
    out_path = os.path.join(os.path.dirname(__file__), "_precomputed.py")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write('"""Pre-computed IDA* tables for 2x2 solver.\n')
        f.write("\n")
        f.write("AUTO-GENERATED by generate_tables.py — do not edit manually.\n")
        f.write('Regenerate with: python -m cube.domain.solver._2x2.generate_tables\n')
        f.write('"""\n\n')

        f.write("# zlib-compressed, base85-encoded table data\n\n")

        _write_bytes_literal(f, "TWIST_MOVE_Z85", twist_b85)
        _write_bytes_literal(f, "PERM_MOVE_Z85", perm_b85)
        _write_bytes_literal(f, "PRUNING_Z85", pruning_b85)

    print(f"Written: {out_path}")
    print(f"File size: {os.path.getsize(out_path):,} bytes")


def _write_bytes_literal(f: object, name: str, data: bytes, line_width: int = 76) -> None:
    """Write a bytes literal spread across multiple lines."""
    f.write(f"{name} = (\n")  # type: ignore[union-attr]
    text = data.decode("ascii")
    for i in range(0, len(text), line_width):
        chunk = text[i:i + line_width]
        f.write(f'    b"{chunk}"\n')  # type: ignore[union-attr]
    f.write(")\n\n")  # type: ignore[union-attr]


if __name__ == "__main__":
    generate()
